spring.application.name=orchestrator

server.port=8080

services.postgres.url=http://localhost:8081
services.mongodb.url=http://localhost:8082

logging.level.com.microservice.orchestrator=DEBUG
logging.level.feign=DEBUG